export type TheoryTopic = {
  id: string
  title: string
  unit: string
  scope: string
  prerequisites: string
  objectives: string
  lesson?: string
}

export const THEORY_TOPICS: TheoryTopic[] = [
  {
    id: 'pitch-octave-pitch-class',
    title: 'Pitch, octave, and pitch class',
    unit: '1 — Pitch on the guitar',
    scope: 'Pitch vs octave vs pitch class.',
    prerequisites: 'None.',
    objectives: 'Distinguish pitch from pitch class; explain same letter in different octaves.',
    lesson: '01-pitch-octave-pitch-class.md',
  },
  {
    id: 'twelve-pitch-classes',
    title: 'The twelve pitch classes',
    unit: '1 — Pitch on the guitar',
    scope: 'Musical alphabet; sharps and flats; enharmonic spelling.',
    prerequisites: 'Pitch, octave, and pitch class.',
    objectives: 'List the twelve classes; explain why spelling matters for scales and chords.',
    lesson: '02-twelve-pitch-classes.md',
  },
  {
    id: 'half-and-whole-steps',
    title: 'Half steps and whole steps',
    unit: '1 — Pitch on the guitar',
    scope: 'Semitone and whole tone; one fret equals one half step.',
    prerequisites: 'The twelve pitch classes.',
    objectives: 'Measure distances in half steps; use frets as the measuring tool.',
    lesson: '03-half-and-whole-steps.md',
  },
  {
    id: 'tuning-and-open-strings',
    title: 'Tuning and the open strings',
    unit: '1 — Pitch on the guitar',
    scope: 'Standard tuning; open strings as pitch-class anchors.',
    prerequisites: 'Twelve pitch classes; half and whole steps.',
    objectives: 'Name the open strings; count frets as half steps from open.',
    lesson: '04-tuning-and-open-strings.md',
  },
  {
    id: 'locating-pitch-classes',
    title: 'Locating pitch classes on the neck',
    unit: '1 — Pitch on the guitar',
    scope: 'Finding one pitch class in multiple places (frets 0–12).',
    prerequisites: 'Half and whole steps; tuning.',
    objectives: 'Find several locations for any pitch class; treat duplicates as octaves or unisons.',
    lesson: '05-locating-pitch-classes.md',
  },
  {
    id: 'octaves-on-the-neck',
    title: 'Octave relationships on the neck',
    unit: '1 — Pitch on the guitar',
    scope: 'Twelve frets up; cross-string octave geometry as a tool, not an axiom.',
    prerequisites: 'Pitch/octave/pitch class; locating pitch classes.',
    objectives: 'Move a known pitch class to another octave location on purpose.',
    lesson: '06-octaves-on-the-neck.md',
  },
  {
    id: 'fretboard-memorization',
    title: 'Fretboard memorization',
    unit: '1 — Pitch on the guitar',
    scope: 'Drill pitch-class recall by string and/or note filters (frets 0–12).',
    prerequisites: 'Twelve pitch classes; half steps; tuning.',
    objectives: 'Name the pitch class at any string and fret quickly.',
  },
  {
    id: 'interval-names-and-quality',
    title: 'Interval names and quality',
    unit: '2 — Intervals',
    scope: 'Interval numbers; major/minor/perfect/diminished/augmented; half-step sizes.',
    prerequisites: 'Half and whole steps.',
    objectives: 'Name intervals and map quality to half-step count.',
    lesson: '07-interval-names-and-quality.md',
  },
  {
    id: 'interval-spelling-and-inversion',
    title: 'Interval spelling and inversion',
    unit: '2 — Intervals',
    scope: 'Correct letter spelling; compound intervals; inversion.',
    prerequisites: 'Interval names and quality.',
    objectives: 'Spell intervals; invert simple intervals; handle compounds.',
    lesson: '08-interval-spelling-and-inversion.md',
  },
  {
    id: 'intervals-in-music',
    title: 'Intervals in music',
    unit: '2 — Intervals',
    scope: 'Melodic vs harmonic use; ear; context-dependent tendency.',
    prerequisites: 'Interval spelling and inversion.',
    objectives: 'Hear and apply common intervals; relate them to scales and chords.',
    lesson: '09-intervals-in-music.md',
  },
  {
    id: 'intervals-on-the-neck',
    title: 'Intervals on the neck',
    unit: '2 — Intervals',
    scope: 'One-string and cross-string interval fingerings.',
    prerequisites: 'Locating pitch classes; interval names.',
    objectives: 'Play a named interval from a root in more than one fingering.',
    lesson: '10-intervals-on-the-neck.md',
  },
  {
    id: 'major-scale-construction',
    title: 'Constructing the major scale',
    unit: '3 — Scales and tonality',
    scope: 'W–W–H–W–W–W–H with unique letter names.',
    prerequisites: 'Half and whole steps.',
    objectives: 'Build any major scale by steps with correct spelling.',
    lesson: '11-major-scale-construction.md',
  },
  {
    id: 'scale-degrees-and-formulas',
    title: 'Scale degrees and formulas',
    unit: '3 — Scales and tonality',
    scope: 'Degrees 1–7; formula notation across keys.',
    prerequisites: 'Constructing the major scale.',
    objectives: 'Translate between note names and degree formulas.',
    lesson: '12-scale-degrees-and-formulas.md',
  },
  {
    id: 'keys-signatures-circle',
    title: 'Keys, signatures, and the circle of fifths',
    unit: '3 — Scales and tonality',
    scope: 'Tonality; key signatures; circle of fifths as key organization.',
    prerequisites: 'Major scale; scale degrees.',
    objectives: 'Explain “in the key of X”; use signatures and the circle practically.',
    lesson: '13-keys-signatures-circle.md',
  },
  {
    id: 'major-scale-on-neck',
    title: 'The major scale on the neck',
    unit: '3 — Scales and tonality',
    scope: 'Construct and connect major scales across the neck.',
    prerequisites: 'Locating notes; intervals on the neck; major scale; degrees.',
    objectives: 'Play major while naming degrees; link positions by shared pitch classes.',
    lesson: '14-major-scale-on-neck.md',
  },
  {
    id: 'natural-minor-relative-parallel',
    title: 'Natural minor; relative and parallel keys',
    unit: '3 — Scales and tonality',
    scope: 'Natural minor; relative and parallel major/minor.',
    prerequisites: 'Keys and signatures; major scale on the neck.',
    objectives: 'Build natural minor; relate relative and parallel keys.',
    lesson: '15-natural-minor-relative-parallel.md',
  },
  {
    id: 'harmonic-melodic-minor',
    title: 'Harmonic and melodic minor',
    unit: '3 — Scales and tonality',
    scope: 'Raised 7; raised 6 and 7; leading-tone function.',
    prerequisites: 'Natural minor; relative and parallel keys.',
    objectives: 'Build harmonic and melodic minor; explain why natural minor’s 7 is often raised.',
    lesson: '16-harmonic-melodic-minor.md',
  },
  {
    id: 'pentatonic-and-blues',
    title: 'Pentatonic and blues',
    unit: '3 — Scales and tonality',
    scope: 'Major/minor pentatonic as subsets; blues ♭5 as color.',
    prerequisites: 'Scale degrees; major on neck; natural minor.',
    objectives: 'Derive pentatonic formulas; use them knowingly against chords.',
    lesson: '17-pentatonic-and-blues.md',
  },
  {
    id: 'modes-in-context',
    title: 'Modes in context',
    unit: '3 — Scales and tonality',
    scope: 'Rotations and characteristic degrees; modal vs functional situations.',
    prerequisites: 'Degrees; major on neck; natural minor.',
    objectives: 'Build a mode for a clear musical situation without treating modes as isolated boxes.',
    lesson: '18-modes-in-context.md',
  },
  {
    id: 'triad-construction',
    title: 'Triad construction',
    unit: '4 — Triads',
    scope: 'Stacking thirds; major, minor, diminished, augmented; spelling.',
    prerequisites: 'Intervals; scale degrees.',
    objectives: 'Build and spell all four triad qualities from any root.',
    lesson: '19-triad-construction.md',
  },
  {
    id: 'triad-inversions',
    title: 'Triad inversions',
    unit: '4 — Triads',
    scope: 'Root position, first and second inversion; bass vs root; inversion vs voicing.',
    prerequisites: 'Triad construction.',
    objectives: 'Identify inversion from the bass; write all inversions of a triad.',
    lesson: '20-triad-inversions.md',
  },
  {
    id: 'triads-on-string-sets',
    title: 'Triads on guitar string sets',
    unit: '4 — Triads',
    scope: 'Close triads on string sets; locate root, third, and fifth.',
    prerequisites: 'Intervals on the neck; triad construction; inversions.',
    objectives: 'Play all inversions of a triad on a chosen string set within a fret range.',
    lesson: '21-triads-on-string-sets.md',
  },
  {
    id: 'diatonic-triads',
    title: 'Diatonic triads',
    unit: '4 — Triads',
    scope: 'Harmonize major (and natural minor); Roman numerals for triads.',
    prerequisites: 'Keys; triad construction.',
    objectives: 'Derive diatonic triad qualities; label them in a key.',
    lesson: '22-diatonic-triads.md',
  },
  {
    id: 'triad-voice-leading',
    title: 'Triad voice leading',
    unit: '4 — Triads',
    scope: 'Connect nearby inversions; common tones; minimal motion.',
    prerequisites: 'Inversions; string-set triads; diatonic triads.',
    objectives: 'Voice-lead a short triad progression on one string set.',
    lesson: '23-triad-voice-leading.md',
  },
  {
    id: 'triads-in-progressions',
    title: 'Triads in progressions and improvisation',
    unit: '4 — Triads',
    scope: 'Rhythm use; outlining harmony; melodic use of chord tones.',
    prerequisites: 'Diatonic triads; triad voice leading.',
    objectives: 'Use triads for changes and simple chord-tone lines.',
    lesson: '24-triads-in-progressions.md',
  },
  {
    id: 'seventh-chords',
    title: 'Seventh chords',
    unit: '5 — Seventh chords and functional harmony',
    scope: 'maj7, m7, dominant 7, m7♭5, dim7.',
    prerequisites: 'Triad construction.',
    objectives: 'Build common sevenths from formulas; hear dominant tension in context.',
    lesson: '25-seventh-chords.md',
  },
  {
    id: 'sevenths-on-guitar',
    title: 'Sevenths on the guitar',
    unit: '5 — Seventh chords and functional harmony',
    scope: 'Shell voicings; inversions; finding the third and seventh.',
    prerequisites: 'Triads on string sets; seventh chords.',
    objectives: 'Play shell voicings; name guide tones inside a grip.',
    lesson: '26-sevenths-on-guitar.md',
  },
  {
    id: 'diatonic-harmony',
    title: 'Diatonic harmony',
    unit: '5 — Seventh chords and functional harmony',
    scope: 'Diatonic seventh sets; Roman numerals; minor overview.',
    prerequisites: 'Diatonic triads; seventh chords.',
    objectives: 'Derive diatonic chords of a major key; label progressions.',
    lesson: '27-diatonic-harmony.md',
  },
  {
    id: 'functional-progressions',
    title: 'Functional progressions',
    unit: '5 — Seventh chords and functional harmony',
    scope: 'Tonic, predominant, dominant; common progressions.',
    prerequisites: 'Diatonic harmony.',
    objectives: 'Explain V→I; build and analyze short progressions.',
    lesson: '28-functional-progressions.md',
  },
  {
    id: 'secondary-dominants',
    title: 'Secondary dominants',
    unit: '5 — Seventh chords and functional harmony',
    scope: 'V/x and temporary tonicization.',
    prerequisites: 'Functional progressions.',
    objectives: 'Spot and build secondary dominants in major keys.',
    lesson: '29-secondary-dominants.md',
  },
  {
    id: 'borrowed-chords',
    title: 'Borrowed chords and modal interchange',
    unit: '5 — Seventh chords and functional harmony',
    scope: 'Common borrows such as ♭VII, ♭VI, and iv.',
    prerequisites: 'Functional progressions; natural minor.',
    objectives: 'Explain and apply frequent interchange chords.',
    lesson: '30-borrowed-chords.md',
  },
  {
    id: 'chord-substitutions',
    title: 'Chord substitutions',
    unit: '5 — Seventh chords and functional harmony',
    scope: 'Relative substitutes; practical dominant substitutes including tritone sub intro.',
    prerequisites: 'Functional progressions; secondary dominants.',
    objectives: 'Substitute with harmonic reason, not random swaps.',
    lesson: '31-chord-substitutions.md',
  },
  {
    id: 'voice-leading-guide-tones',
    title: 'Voice leading and guide tones',
    unit: '5 — Seventh chords and functional harmony',
    scope: 'Guide-tone lines; shells; connecting seventh chords on the neck.',
    prerequisites: 'Triad voice leading; sevenths on guitar; functional progressions.',
    objectives: 'Voice-lead ii–V–I with clear 3rd/7th motion.',
    lesson: '32-voice-leading-guide-tones.md',
  },
  {
    id: 'caged-navigation',
    title: 'CAGED as navigation',
    unit: '6 — Fretboard systems and improvisation',
    scope: 'Overlapping chord/scale maps as orientation, not dogma.',
    prerequisites: 'Major on neck; triad string sets; sevenths on guitar.',
    objectives: 'Locate chord/scale areas via CAGED without treating shapes as the theory.',
    lesson: '33-caged-navigation.md',
  },
  {
    id: 'three-notes-per-string',
    title: 'Three-notes-per-string scales',
    unit: '6 — Fretboard systems and improvisation',
    scope: '3NPS as organization for horizontal movement.',
    prerequisites: 'Major scale on the neck.',
    objectives: 'Connect major (then minor) 3NPS positions by shared degrees.',
    lesson: '34-three-notes-per-string.md',
  },
  {
    id: 'arpeggios-chord-tones',
    title: 'Arpeggios and chord-tone targeting',
    unit: '6 — Fretboard systems and improvisation',
    scope: 'Chord tones as lines; strong-beat targeting.',
    prerequisites: 'Triads in progressions; sevenths on guitar; functional progressions.',
    objectives: 'Outline a progression; land chord tones deliberately.',
    lesson: '35-arpeggios-chord-tones.md',
  },
  {
    id: 'improvising-through-changes',
    title: 'Improvising through chord changes',
    unit: '6 — Fretboard systems and improvisation',
    scope: 'Chord tones first; approach notes; scales as resources.',
    prerequisites: 'Pentatonic and blues; arpeggios; functional progressions.',
    objectives: 'Improvise a short chorus with audible awareness of the changes.',
    lesson: '36-improvising-through-changes.md',
  },
  {
    id: 'pulse-and-feel',
    title: 'Pulse, subdivision, and feel',
    unit: '7 — Time, melody, and musical independence',
    scope: 'Beat, bar, common subdivisions; straight vs swing.',
    prerequisites: 'Basic counting.',
    objectives: 'Lock subdivisions to a pulse; change feel without changing harmony.',
    lesson: '37-pulse-and-feel.md',
  },
  {
    id: 'melody-motif-phrasing',
    title: 'Melody, motif, and phrasing',
    unit: '7 — Time, melody, and musical independence',
    scope: 'Motifs; development; articulation; tension and release in lines.',
    prerequisites: 'Intervals in music; arpeggios; pulse and feel.',
    objectives: 'Build a short motif-based phrase that respects underlying chords.',
    lesson: '38-melody-motif-phrasing.md',
  },
  {
    id: 'analyzing-real-music',
    title: 'Analyzing real music',
    unit: '7 — Time, melody, and musical independence',
    scope: 'Independent analysis of unfamiliar progressions and melodies.',
    prerequisites: 'Diatonic harmony; functional progressions; arpeggios.',
    objectives: 'Find key, Roman numerals, function, and chord tones without being handed answers.',
    lesson: '39-analyzing-real-music.md',
  },
  {
    id: 'transposition-and-creation',
    title: 'Transposition and musical creation',
    unit: '7 — Time, melody, and musical independence',
    scope: 'Transpose material; compose and improvise with the full toolkit.',
    prerequisites: 'Keys; functional progressions; improvising through changes; melody.',
    objectives: 'Move material across keys; create a short original progression and line.',
    lesson: '40-transposition-and-creation.md',
  },
]

export function getTopic(id: string): TheoryTopic | undefined {
  return THEORY_TOPICS.find((topic) => topic.id === id)
}
