export type TheoryTopic = {
  id: string
  title: string
  unit: string
  scope: string
  prerequisites: string
  objectives: string
  lesson?: string
}

export const THEORY_TOPICS: TheoryTopic[] = [
  {
    id: 'pitch-octave-pitch-class',
    title: 'Pitch, octave, and pitch class',
    unit: '1 — Musical foundations',
    scope: 'Pitch vs octave vs pitch class.',
    prerequisites: 'None.',
    objectives: 'Distinguish pitch from pitch class; explain same letter in different octaves.',
    lesson: '01-pitch-octave-pitch-class.md',
  },
  {
    id: 'twelve-pitch-classes',
    title: 'The twelve pitch classes',
    unit: '1 — Musical foundations',
    scope: 'Musical alphabet; sharps and flats; enharmonic spelling.',
    prerequisites: 'Pitch, octave, and pitch class.',
    objectives: 'List the twelve classes; explain why spelling matters for scales and chords.',
    lesson: '02-twelve-pitch-classes.md',
  },
  {
    id: 'half-and-whole-steps',
    title: 'Half steps and whole steps',
    unit: '1 — Musical foundations',
    scope: 'Semitone and whole tone; one fret equals one half step.',
    prerequisites: 'The twelve pitch classes.',
    objectives: 'Measure distances in half steps; use frets as the measuring tool.',
    lesson: '03-half-and-whole-steps.md',
  },
  {
    id: 'tuning-and-open-strings',
    title: 'Tuning and the open strings',
    unit: '1 — Musical foundations',
    scope: 'Standard tuning; open strings as pitch-class anchors.',
    prerequisites: 'Twelve pitch classes; half and whole steps.',
    objectives: 'Name the open strings; count frets as half steps from open.',
    lesson: '04-tuning-and-open-strings.md',
  },
  {
    id: 'locating-pitch-classes',
    title: 'Locating pitch classes on the neck',
    unit: '1 — Musical foundations',
    scope: 'Finding one pitch class in multiple places (frets 0–12).',
    prerequisites: 'Half and whole steps; tuning.',
    objectives: 'Find several locations for any pitch class.',
    lesson: '05-locating-pitch-classes.md',
  },
  {
    id: 'octaves-on-the-neck',
    title: 'Octave relationships on the neck',
    unit: '1 — Musical foundations',
    scope: 'Twelve frets up; cross-string octave geometry as a tool.',
    prerequisites: 'Pitch/octave/pitch class; locating pitch classes.',
    objectives: 'Move a known pitch class to another octave location on purpose.',
    lesson: '06-octaves-on-the-neck.md',
  },
  {
    id: 'pulse-meter-notation',
    title: 'Pulse, meter, and rhythmic notation',
    unit: '1 — Musical foundations',
    scope: 'Pulse, tempo, meter, time signatures, durations, dots, and ties.',
    prerequisites: 'Basic counting.',
    objectives: 'Read and perform basic rhythmic notation against a steady pulse.',
    lesson: '07-pulse-meter-notation.md',
  },
  {
    id: 'subdivisions-syncopation-feel',
    title: 'Subdivisions, syncopation, and feel',
    unit: '1 — Musical foundations',
    scope: 'Eighths/triplets/sixteenths; syncopation; straight vs swing.',
    prerequisites: 'Pulse, meter, and rhythmic notation.',
    objectives: 'Lock common subdivisions; use syncopation and swing without changing harmony.',
    lesson: '08-subdivisions-syncopation-feel.md',
  },
  {
    id: 'fretboard-memorization',
    title: 'Fretboard memorization',
    unit: '1 — Musical foundations',
    scope: 'Drill pitch-class recall by string and/or note filters (frets 0–12).',
    prerequisites: 'Twelve pitch classes; half steps; tuning.',
    objectives: 'Name the pitch class at any string and fret quickly.',
  },
  {
    id: 'interval-names-and-quality',
    title: 'Interval names and quality',
    unit: '2 — Intervals',
    scope: 'Interval numbers; qualities; half-step sizes.',
    prerequisites: 'Half and whole steps.',
    objectives: 'Name intervals and map quality to half-step count.',
    lesson: '09-interval-names-and-quality.md',
  },
  {
    id: 'interval-spelling-and-inversion',
    title: 'Interval spelling and inversion',
    unit: '2 — Intervals',
    scope: 'Letter spelling; compound intervals; inversion.',
    prerequisites: 'Interval names and quality.',
    objectives: 'Spell intervals; invert simple intervals; handle compounds.',
    lesson: '10-interval-spelling-and-inversion.md',
  },
  {
    id: 'intervals-in-music',
    title: 'Intervals in music',
    unit: '2 — Intervals',
    scope: 'Melodic vs harmonic use; ear; context-dependent tendency.',
    prerequisites: 'Interval spelling and inversion.',
    objectives: 'Hear and apply common intervals; relate them to scales and chords.',
    lesson: '11-intervals-in-music.md',
  },
  {
    id: 'intervals-on-the-neck',
    title: 'Intervals on the neck',
    unit: '2 — Intervals',
    scope: 'One-string and cross-string interval fingerings.',
    prerequisites: 'Locating pitch classes; interval names.',
    objectives: 'Play a named interval from a root in more than one fingering.',
    lesson: '12-intervals-on-the-neck.md',
  },
  {
    id: 'major-scale-construction',
    title: 'Constructing the major scale',
    unit: '3 — Major scale and tonality',
    scope: 'W–W–H–W–W–W–H with unique letter names.',
    prerequisites: 'Half and whole steps.',
    objectives: 'Build any major scale by steps with correct spelling.',
    lesson: '13-major-scale-construction.md',
  },
  {
    id: 'scale-degrees-and-formulas',
    title: 'Scale degrees and formulas',
    unit: '3 — Major scale and tonality',
    scope: 'Degrees 1–7; formula notation across keys.',
    prerequisites: 'Constructing the major scale.',
    objectives: 'Translate between note names and degree formulas.',
    lesson: '14-scale-degrees-and-formulas.md',
  },
  {
    id: 'keys-signatures-circle',
    title: 'Keys, signatures, and the circle of fifths',
    unit: '3 — Major scale and tonality',
    scope: 'Tonality; key signatures; circle of fifths.',
    prerequisites: 'Major scale; scale degrees.',
    objectives: 'Explain “in the key of X”; use signatures and the circle practically.',
    lesson: '15-keys-signatures-circle.md',
  },
  {
    id: 'major-scale-on-neck',
    title: 'The major scale on the neck',
    unit: '3 — Major scale and tonality',
    scope: 'Construct and connect major scales across the neck.',
    prerequisites: 'Intervals on the neck; major scale; degrees.',
    objectives: 'Play major while naming degrees; link positions by shared pitch classes.',
    lesson: '16-major-scale-on-neck.md',
  },
  {
    id: 'triad-construction',
    title: 'Triad construction',
    unit: '4 — Triads and basic arpeggios',
    scope: 'Stacking thirds; major, minor, diminished, augmented.',
    prerequisites: 'Intervals; scale degrees.',
    objectives: 'Build and spell all four triad qualities from any root.',
    lesson: '17-triad-construction.md',
  },
  {
    id: 'triad-inversions',
    title: 'Triad inversions',
    unit: '4 — Triads and basic arpeggios',
    scope: 'Root position and inversions; bass vs root; inversion vs voicing.',
    prerequisites: 'Triad construction.',
    objectives: 'Identify inversion from the bass; write all inversions of a triad.',
    lesson: '18-triad-inversions.md',
  },
  {
    id: 'triads-on-string-sets',
    title: 'Triads on guitar string sets',
    unit: '4 — Triads and basic arpeggios',
    scope: 'Derive close triads on string sets; locate R/3/5.',
    prerequisites: 'Triad inversions; intervals on the neck.',
    objectives: 'Construct inversions on a string set from notes, not memorized grids alone.',
    lesson: '19-triads-on-string-sets.md',
  },
  {
    id: 'triad-arpeggios',
    title: 'Triad arpeggios',
    unit: '4 — Triads and basic arpeggios',
    scope: 'Unfold triad tones melodically across inversions and sets.',
    prerequisites: 'Triads on string sets.',
    objectives: 'Arpeggiate major/minor triads in inversions and outline a short progression.',
    lesson: '20-triad-arpeggios.md',
  },
  {
    id: 'diatonic-triads',
    title: 'Diatonic triads',
    unit: '5 — Diatonic harmony',
    scope: 'Harmonize the major scale; Roman numerals for triads.',
    prerequisites: 'Keys; triad construction.',
    objectives: 'Derive diatonic triad qualities; label them in a key.',
    lesson: '21-diatonic-triads.md',
  },
  {
    id: 'triad-voice-leading',
    title: 'Triad voice leading',
    unit: '5 — Diatonic harmony',
    scope: 'Common tones; minimal motion between nearby inversions.',
    prerequisites: 'Diatonic triads; string-set triads.',
    objectives: 'Voice-lead a short triad progression on one string set.',
    lesson: '22-triad-voice-leading.md',
  },
  {
    id: 'cadences-and-harmonic-motion',
    title: 'Cadences and harmonic motion',
    unit: '5 — Diatonic harmony',
    scope: 'Authentic, half, plagal, deceptive cadences; basic function.',
    prerequisites: 'Diatonic triads; triad voice leading.',
    objectives: 'Build and recognize common cadences; relate them to tonic/predominant/dominant jobs.',
    lesson: '23-cadences-and-harmonic-motion.md',
  },
  {
    id: 'triads-in-progressions',
    title: 'Triads in progressions and improvisation',
    unit: '5 — Diatonic harmony',
    scope: 'Comping, outlining, and chord-tone melody with triads.',
    prerequisites: 'Cadences; triad voice leading; triad arpeggios.',
    objectives: 'Play a progression with nearby inversions and a chord-tone melody.',
    lesson: '24-triads-in-progressions.md',
  },
  {
    id: 'caged-navigation',
    title: 'CAGED as navigation',
    unit: '6 — Fretboard organization',
    scope: 'Overlapping chord/scale maps for roots, tones, and positions.',
    prerequisites: 'Triad string sets; major scale on the neck.',
    objectives: 'Navigate chord tones and nearby scale notes via CAGED without shape dogma.',
    lesson: '25-caged-navigation.md',
  },
  {
    id: 'pentatonic-and-blues',
    title: 'Pentatonic and blues',
    unit: '6 — Fretboard organization',
    scope: 'Major/minor pentatonic as subsets; blues ♭5 as color.',
    prerequisites: 'Scale degrees; major scale on the neck; CAGED helpful.',
    objectives: 'Derive pentatonic formulas; use them with chord-tone awareness.',
    lesson: '26-pentatonic-and-blues.md',
  },
  {
    id: 'three-notes-per-string',
    title: 'Three-notes-per-string scales',
    unit: '6 — Fretboard organization',
    scope: '3NPS as organization for horizontal movement.',
    prerequisites: 'Major scale on the neck; CAGED.',
    objectives: 'Connect major 3NPS positions by shared degrees.',
    lesson: '27-three-notes-per-string.md',
  },
  {
    id: 'natural-minor-relative-parallel',
    title: 'Natural minor; relative and parallel keys',
    unit: '7 — Minor tonality',
    scope: 'Natural minor; relative and parallel major/minor.',
    prerequisites: 'Keys; major scale on the neck.',
    objectives: 'Build natural minor; relate relative and parallel keys.',
    lesson: '28-natural-minor-relative-parallel.md',
  },
  {
    id: 'harmonic-melodic-minor',
    title: 'Harmonic and melodic minor',
    unit: '7 — Minor tonality',
    scope: 'Raised 7; raised 6 and 7; leading-tone function.',
    prerequisites: 'Natural minor.',
    objectives: 'Build harmonic and melodic minor; explain why 7 is often raised.',
    lesson: '29-harmonic-melodic-minor.md',
  },
  {
    id: 'minor-key-harmony',
    title: 'Minor-key harmony',
    unit: '7 — Minor tonality',
    scope: 'Natural-minor diatonic chords; V/V7 from harmonic minor; minor cadences.',
    prerequisites: 'Natural/harmonic minor; diatonic triads.',
    objectives: 'Analyze and play common minor progressions with correct RN and leading tones.',
    lesson: '30-minor-key-harmony.md',
  },
  {
    id: 'seventh-chords',
    title: 'Seventh chords',
    unit: '8 — Seventh chords and extensions',
    scope: 'maj7, m7, dominant 7, m7♭5, dim7.',
    prerequisites: 'Triad construction.',
    objectives: 'Build common sevenths from formulas; hear dominant tension in context.',
    lesson: '31-seventh-chords.md',
  },
  {
    id: 'sevenths-on-guitar',
    title: 'Sevenths on the guitar',
    unit: '8 — Seventh chords and extensions',
    scope: 'Shells; inversions; finding 3 and 7.',
    prerequisites: 'Seventh chords; triad string sets.',
    objectives: 'Play shell voicings; name guide tones inside a grip.',
    lesson: '32-sevenths-on-guitar.md',
  },
  {
    id: 'diatonic-harmony',
    title: 'Diatonic seventh harmony',
    unit: '8 — Seventh chords and extensions',
    scope: 'Diatonic seventh sets in major; RN; link to minor overview.',
    prerequisites: 'Diatonic triads; seventh chords.',
    objectives: 'Derive diatonic sevenths of a major key; label progressions.',
    lesson: '33-diatonic-seventh-harmony.md',
  },
  {
    id: 'chord-extensions-sus-add',
    title: 'Suspensions, added tones, and extensions',
    unit: '8 — Seventh chords and extensions',
    scope: 'sus, add, 6, 9/11/13, alterations; guitar omissions.',
    prerequisites: 'Sevenths on the guitar.',
    objectives: 'Spell and distinguish Cadd9 vs C9 vs Csus2 vs Cmaj9 vs C6; voice practical grips.',
    lesson: '34-chord-extensions-sus-add.md',
  },
  {
    id: 'voice-leading-guide-tones',
    title: 'Voice leading and guide tones',
    unit: '8 — Seventh chords and extensions',
    scope: 'Guide-tone lines; shells; connecting seventh chords.',
    prerequisites: 'Sevenths on guitar; triad voice leading.',
    objectives: 'Voice-lead ii–V–I with clear 3rd/7th motion.',
    lesson: '35-voice-leading-guide-tones.md',
  },
  {
    id: 'functional-progressions',
    title: 'Functional progressions',
    unit: '9 — Functional and chromatic harmony',
    scope: 'Tonic, predominant, dominant; common progressions.',
    prerequisites: 'Diatonic seventh harmony; cadences.',
    objectives: 'Explain V→I; build and analyze short progressions.',
    lesson: '36-functional-progressions.md',
  },
  {
    id: 'secondary-dominants',
    title: 'Secondary dominants',
    unit: '9 — Functional and chromatic harmony',
    scope: 'V/x; tonicization vs modulation.',
    prerequisites: 'Functional progressions.',
    objectives: 'Spot and build secondary dominants in major keys.',
    lesson: '37-secondary-dominants.md',
  },
  {
    id: 'borrowed-chords',
    title: 'Borrowed chords and modal interchange',
    unit: '9 — Functional and chromatic harmony',
    scope: 'Common borrows such as ♭VII, ♭VI, and iv.',
    prerequisites: 'Functional progressions; natural minor.',
    objectives: 'Explain and apply frequent interchange chords.',
    lesson: '38-borrowed-chords.md',
  },
  {
    id: 'chord-substitutions',
    title: 'Chord substitutions',
    unit: '9 — Functional and chromatic harmony',
    scope: 'Relative and dominant substitutes; tritone-sub intro.',
    prerequisites: 'Functional progressions; secondary dominants.',
    objectives: 'Substitute with harmonic reason, not random swaps.',
    lesson: '39-chord-substitutions.md',
  },
  {
    id: 'modes-in-context',
    title: 'Modes in context',
    unit: '10 — Modes and modal harmony',
    scope: 'Construction; characteristic degrees; modal vs functional harmony.',
    prerequisites: 'Functional harmony; major/minor fluency.',
    objectives: 'Choose and justify a mode for a vamp or progression context.',
    lesson: '40-modes-in-context.md',
  },
  {
    id: 'arpeggios-chord-tones',
    title: 'Arpeggios and chord-tone targeting',
    unit: '11 — Improvisation and melodic development',
    scope: 'Seventh arpeggios; strong-beat targeting; connections.',
    prerequisites: 'Triad arpeggios; sevenths; functional progressions.',
    objectives: 'Outline changes with arpeggios; land chord tones deliberately.',
    lesson: '41-arpeggios-chord-tones.md',
  },
  {
    id: 'improvising-through-changes',
    title: 'Improvising through chord changes',
    unit: '11 — Improvisation and melodic development',
    scope: 'Chord tones first; approaches; scales as resources.',
    prerequisites: 'Arpeggios; pentatonic; functional progressions.',
    objectives: 'Improvise a short chorus with audible awareness of the changes.',
    lesson: '42-improvising-through-changes.md',
  },
  {
    id: 'melody-motif-phrasing',
    title: 'Melody, motif, and phrasing',
    unit: '11 — Improvisation and melodic development',
    scope: 'Motifs; sequences; phrase structure; tension/release; rhythmic development.',
    prerequisites: 'Intervals; arpeggios; subdivisions and feel.',
    objectives: 'Develop a motif over changing harmony with clear phrasing.',
    lesson: '43-melody-motif-phrasing.md',
  },
  {
    id: 'analyzing-real-music',
    title: 'Analyzing real music',
    unit: '12 — Musical analysis and creation',
    scope: 'Independent analysis of progressions and melodies.',
    prerequisites: 'Functional harmony; arpeggios.',
    objectives: 'Produce a defensible RN analysis and chord-tone reading of a melody.',
    lesson: '44-analyzing-real-music.md',
  },
  {
    id: 'transposition-and-creation',
    title: 'Transposition and musical creation',
    unit: '12 — Musical analysis and creation',
    scope: 'Transpose; compose; reharmonize lightly; integrate the toolkit.',
    prerequisites: 'Keys; functional harmony; improvisation; melody.',
    objectives: 'Move material across keys; create a short original progression and line.',
    lesson: '45-transposition-and-creation.md',
  },
]

export function getTopic(id: string): TheoryTopic | undefined {
  return THEORY_TOPICS.find((topic) => topic.id === id)
}
